# MERGING DATA USING PANDAS

## Basic Merging

In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame({
    "Id":[1,2,3],
    "Name":["Asha","Binu","Cathy"]
})
df2=pd.DataFrame({
    "Id":[1,2,4],
    "Marks":[85,90,75]
})
merged_df=pd.merge(df1,df2,on="Id")
print(merged_df)

   Id  Name  Marks
0   1  Asha     85
1   2  Binu     90

# TYPES OF JOINS

## Inner Join(default)

### Only Common Rows:

In [3]:
pd.merge(df1,df2,on="Id",how="inner")

   Id  Name  Marks
0   1  Asha     85
1   2  Binu     90

## Left Join

### All Rows From Left DataFrame:

In [4]:
pd.merge(df1,df2,on="Id",how="left")

   Id   Name  Marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN

## Right Join

### All Rows From Right DataFrame:

In [5]:
pd.merge(df1,df2,on="Id",how="right")

   Id  Name  Marks
0   1  Asha     85
1   2  Binu     90
2   4   NaN     75

## Outer Join

### All Rows From Both:

In [6]:
pd.merge(df1,df2,on="Id",how="outer")

   Id   Name  Marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN
3   4    NaN   75.0

## Merge on Different Column Names

In [7]:
df1=pd.DataFrame({
    "Id":[1,2,3],
    "Name":["Asha","Binu","Cathy"]
})
df2=pd.DataFrame({
    "Student_Id":[1,2,4],
    "Marks":[85,90,75]
})
merged_df=pd.merge(df1,df2,left_on="Id",right_on="Student_Id")
print(merged_df)

   Id  Name  Student_Id  Marks
0   1  Asha           1     85
1   2  Binu           2     90

## Concatenation

#### Row Wise

In [8]:
pd.concat([df1,df2],axis=0)

    Id   Name  Student_Id  Marks
0  1.0   Asha         NaN    NaN
1  2.0   Binu         NaN    NaN
2  3.0  Cathy         NaN    NaN
0  NaN    NaN         1.0   85.0
1  NaN    NaN         2.0   90.0
2  NaN    NaN         4.0   75.0

#### Column Wise

In [9]:
pd.concat([df1,df2],axis=1)

   Id   Name  Student_Id  Marks
0   1   Asha           1     85
1   2   Binu           2     90
2   3  Cathy           4     75

## Apply

In [10]:
mark=pd.Series([45,60,75,90])
def grade(x):
    if x>50:
        return "Pass"
    else:
        return "Fail"
print(mark.apply(grade))

0    Fail
1    Pass
2    Pass
3    Pass
dtype: object

## Apply Using Lambda Function

In [13]:
mark=pd.Series([45,60,75,90])
result=mark.apply(lambda x:x+5)
print(result)

0    50
1    65
2    80
3    95
dtype: int64

## Apply() On DataFrame Columns

In [14]:
df=pd.DataFrame({
    "Math":[80,70,90],
    "Science":[85,60,95]
})
print(df.apply(max))

Math       90
Science    95
dtype: int64