## DATA INTEGRATION AND TRANSFORMATION TASK

In [2]:
import pandas as pd

In [3]:
df1=pd.DataFrame({
    "Roll_no":[1,2,3,4,5],
    "Name":["Binu","Sanju","Yamin","Anu","Sali"],
    "Mark":[70,75,89,95,90]
})
df2=pd.DataFrame({
    "Roll_no":[1,2,3,6,7],
    "Grade":["B","B+","A","A+","A+"],
    "Class":[8,9,10,11,12]
})
merged_df=pd.merge(df1,df2,on="Roll_no")
print(merged_df)

   Roll_no   Name  Mark Grade  Class
0        1   Binu    70     B      8
1        2  Sanju    75    B+      9
2        3  Yamin    89     A     10

### Inner Join

In [4]:
pd.merge(df1,df2,on="Roll_no",how="inner")

   Roll_no   Name  Mark Grade  Class
0        1   Binu    70     B      8
1        2  Sanju    75    B+      9
2        3  Yamin    89     A     10

### Left Join

In [6]:
pd.merge(df1,df2,on="Roll_no",how="left")

   Roll_no   Name  Mark Grade  Class
0        1   Binu    70     B    8.0
1        2  Sanju    75    B+    9.0
2        3  Yamin    89     A   10.0
3        4    Anu    95   NaN    NaN
4        5   Sali    90   NaN    NaN

### Right Join

In [7]:
pd.merge(df1,df2,on="Roll_no",how="right")

   Roll_no   Name  Mark Grade  Class
0        1   Binu  70.0     B      8
1        2  Sanju  75.0    B+      9
2        3  Yamin  89.0     A     10
3        6    NaN   NaN    A+     11
4        7    NaN   NaN    A+     12

### Outer Join

In [8]:
pd.merge(df1,df2,on="Roll_no",how="outer")

   Roll_no   Name  Mark Grade  Class
0        1   Binu  70.0     B    8.0
1        2  Sanju  75.0    B+    9.0
2        3  Yamin  89.0     A   10.0
3        4    Anu  95.0   NaN    NaN
4        5   Sali  90.0   NaN    NaN
5        6    NaN   NaN    A+   11.0
6        7    NaN   NaN    A+   12.0

### Merge on Different Column Names

In [9]:
df1=pd.DataFrame({
    "Roll_no":[1,2,3,4,5],
    "Name":["Binu","Sanju","Yamin","Anu","Sali"],
    "Mark":[70,75,89,95,90]
})
df2=pd.DataFrame({
    "ID":[1,2,3,6,7],
    "Grade":["B","B+","A","A+","A+"],
    "Class":[8,9,10,11,12]
})
merged_df=pd.merge(df1,df2,left_on="Roll_no",right_on="ID")
print(merged_df)

   Roll_no   Name  Mark  ID Grade  Class
0        1   Binu    70   1     B      8
1        2  Sanju    75   2    B+      9
2        3  Yamin    89   3     A     10

### Concatenation

#### Row wise

In [10]:
pd.concat([df1,df2],axis=0)

   Roll_no   Name  Mark   ID Grade  Class
0      1.0   Binu  70.0  NaN   NaN    NaN
1      2.0  Sanju  75.0  NaN   NaN    NaN
2      3.0  Yamin  89.0  NaN   NaN    NaN
3      4.0    Anu  95.0  NaN   NaN    NaN
4      5.0   Sali  90.0  NaN   NaN    NaN
0      NaN    NaN   NaN  1.0     B    8.0
1      NaN    NaN   NaN  2.0    B+    9.0
2      NaN    NaN   NaN  3.0     A   10.0
3      NaN    NaN   NaN  6.0    A+   11.0
4      NaN    NaN   NaN  7.0    A+   12.0

#### Column wise

In [11]:
pd.concat([df1,df2],axis=1)

   Roll_no   Name  Mark  ID Grade  Class
0        1   Binu    70   1     B      8
1        2  Sanju    75   2    B+      9
2        3  Yamin    89   3     A     10
3        4    Anu    95   6    A+     11
4        5   Sali    90   7    A+     12

### Apply

In [12]:
mark=pd.Series([90,45,55,72,80])
def grade(x):
    if x>55:
        return "Pass"
    else:
        return "Fail"
print(mark.apply(grade))

0    Pass
1    Fail
2    Fail
3    Pass
4    Pass
dtype: object

### Apply using Lambda

In [14]:
mark=pd.Series([90,45,55,72,80])
result=mark.apply(lambda x:x+10)
print(result)

0    100
1     55
2     65
3     82
4     90
dtype: int64

### Apply on DataFrame

In [15]:
df=pd.DataFrame({
    "English":[72,45,80],
    "Malayalam":[79,35,70]
})
print(df.apply(min))

English      45
Malayalam    35
dtype: int64

In [16]:
df=pd.DataFrame({
    "English":[72,45,80],
    "Malayalam":[79,35,70]
})
print(df.apply(max))

English      80
Malayalam    79
dtype: int64