# TITANIC DATASET ANALYSIS

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [3]:
# load titanic dataset from csv
df=pd.read_csv("titanic dataset.csv")

In [4]:
# Display the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [5]:
# Display the last 5 rows
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75

In [6]:
# Show number of rows and columns
df.shape

(891, 10)

In [7]:
df.size

8910

In [8]:
# Display column names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare'],
      dtype='object')

In [9]:
# Show datatype of all columns
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
dtype: object

In [10]:
# Display complete information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [11]:
# statistical summary of numerical columns
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### CHECK MISSING VALUES

In [12]:
#chek missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [13]:
# total missing values in dataset
df.isnull().sum().sum()

np.int64(177)

### FILL MISSING VALUES

In [14]:
# fill missing ages with age mean
df["Age"].fillna(df["Age"].mean(),inplace=True)

### RECHECK NULL VALUES

In [15]:
# rechecking if any null values exist
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

In [17]:
# check count for duplicate values
df.duplicated().sum()

np.int64(0)

In [18]:
# display specific column
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [19]:
# display multiple columns
df[["Name","Age","Sex"]]

                                                  Name        Age     Sex
0                              Braund, Mr. Owen Harris  22.000000    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.000000  female
2                               Heikkinen, Miss. Laina  26.000000  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.000000  female
4                             Allen, Mr. William Henry  35.000000    male
..                                                 ...        ...     ...
886                              Montvila, Rev. Juozas  27.000000    male
887                       Graham, Miss. Margaret Edith  19.000000  female
888           Johnston, Miss. Catherine Helen "Carrie"  29.699118  female
889                              Behr, Mr. Karl Howell  26.000000    male
890                                Dooley, Mr. Patrick  32.000000    male

[891 rows x 3 columns]

In [20]:
# display first pacentger record
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Name: 0, dtype: object

In [21]:
# display first fie rows
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [22]:
#display row 0 and columns 1 to 3
df.iloc[0,1:4]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Name: 0, dtype: object

In [23]:
# display passengers older than 30
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500
...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [24]:
# display female passengers
df[df["Sex"]=="female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708
...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,26.0000
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.000000,0,0,7552,10.5167
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,29.1250
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500

In [25]:
# display male passengers
df[df["Sex"]=="male"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750
...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.000000,0,0,C.A./SOTON 34068,10.5000
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,7.0500
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500

In [28]:
# count male and female passengers
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [29]:
# count survived and not survived passengers
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [30]:
# calculate average age
df["Age"].mean()

np.float64(29.69911764705882)

In [31]:
# find maximum age
df["Age"].max()

80.0

In [32]:
# find minimum age
df["Age"].min()

0.42

In [33]:
# calculate median age
df["Age"].median()

29.69911764705882

In [34]:
# calculate sum of fairs
df["Fare"].sum()

np.float64(28693.9493)

In [35]:
# calculate average of fair
df["Fare"].mean()

np.float64(32.204207968574636)

In [37]:
# find oldest passenger
df[df["Age"]==df["Age"].max()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0

In [38]:
# find youngest passenger
df[df["Age"]==df["Age"].min()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167

In [39]:
# sort by age ascending order
df.sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500
...,...,...,...,...,...,...,...,...,...,...
116,117,0,3,"Connors, Mr. Patrick",male,70.50,0,0,370369,7.7500
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042
851,852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000

In [41]:
# sort by age descending order
df.sort_values("Age",ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000
851,852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042
116,117,0,3,"Connors, Mr. Patrick",male,70.50,0,0,370369,7.7500
...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167

In [42]:
# sort by fare descending 
df.sort_values("Fare",ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
258,259,1,1,"Ward, Miss. Anna",female,35.000000,0,0,PC 17755,512.3292
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.000000,0,0,PC 17755,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.000000,0,1,PC 17755,512.3292
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,263.0000
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000
...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",male,29.699118,0,0,112052,0.0000
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,29.699118,0,0,239853,0.0000
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.000000,0,0,19972,0.0000
732,733,0,2,"Knight, Mr. Robert J",male,29.699118,0,0,239855,0.0000
674,675,0,2,"Watson, Mr. Ennis Hastings",male,29.699118,0,0,239856,0.0000

In [43]:
#select passengers from class 1
df[df["Pclass"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000
...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000

In [44]:
# select passengers from class 2
df[df["Pclass"]==2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.000000,0,0,248706,16.0000
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000
20,21,0,2,"Fynney, Mr. Joseph J",male,35.000000,0,0,239865,26.0000
21,22,1,2,"Beesley, Mr. Lawrence",male,34.000000,0,0,248698,13.0000
...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.000000,1,0,SC/PARIS 2149,13.8583
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.000000,1,0,P/PP 3381,24.0000
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,26.0000
883,884,0,2,"Banfield, Mr. Frederick James",male,28.000000,0,0,C.A./SOTON 34068,10.5000
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000

In [45]:
# select passengers from class 3
df[df["Pclass"]==3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750
...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.000000,0,0,7552,10.5167
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,7.0500
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,29.1250
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500

In [46]:
# count passengers in each class
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## groupby()

In [47]:
# average age by passenger class
df.groupby("Pclass")["Age"].mean()

Pclass
1    37.048118
2    29.866958
3    26.403259
Name: Age, dtype: float64

In [48]:
# average fare by passenger class
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [50]:
# survival count by gender
df.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [51]:
# average age by gender
df.groupby("Sex")["Age"].mean()

Sex
female    28.216730
male      30.505824
Name: Age, dtype: float64

### RENAME COLUMN

In [63]:
# rename column
df.rename(columns={"Sex":"Gender"},inplace=True)
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Age_after_5_years,Age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,27.0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,43.0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,31.0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,40.0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,40.0,Adult

### ADD NEW COLUMNS

In [64]:
# add new column age+5
df["Age_after_5_years"]=df["Age"]+5
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Age_after_5_years,Age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,27.0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,43.0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,31.0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,40.0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,40.0,Adult

In [65]:
# add age category column
df["Age_group"]=df["Age"].apply(
    lambda x:"Child" if x<18 else "Adult"
)
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Age_after_5_years,Age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,27.0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,43.0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,31.0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,40.0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,40.0,Adult

In [67]:
# display unique gender values
df["Gender"].unique()

array(['male', 'female'], dtype=object)

In [68]:
# count unique gender values
df["Gender"].value_counts()

Gender
male      577
female    314
Name: count, dtype: int64

### SAVE MODIFIED DATASET

In [69]:
df.to_csv("new_titanic dataset.csv",index=False)